name: debugger-action
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debugger Session
        uses: neilpang/debugger-action@master
