# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkNgrokToken:
    runs-on: ubuntu-latest
    outputs:
      action_fruit: ${{ steps.check.outputs.action_fruit }}
    env: 
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
    steps:
    - name: check
      id: checkid
      run: |
          echo "::set-output name=ischeck::'true'\n"
          echo "::set-output name=action_fruit::strawberry"
      
  test:
    runs-on: ubuntu-latest
    needs: checkNgrokToken
    steps:
    - name: check2
      run: |
            echo "${{needs.checkNgrokToken.outputs.checkid.action_fruit}}"  
            echo "${{github.actor}}"
  Windows:
    runs-on: windows-latest
    needs: checkNgrokToken
    if: contains(needs.checkNgrokToken.outputs , 'true')
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
      Le_HTTPPort: 8888
    steps:
    - uses: actions/checkout@v2
    - name: Install cygwin base packages with chocolatey
      run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
      shell: cmd
    - name: Install cygwin additional packages
      run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P socat,curl,cron,unzip,git
      shell: cmd
    - name: Set ENV
      run: |
          echo '::set-env name=PATH::C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin'
    - name: Clone acmetest
      shell: cmd
      run: cd .. && git clone https://github.com/acmesh-official/acmetest.git  && cp -r test acmetest/
    - name: Run acmetest
      shell: cmd
      run: cd ../acmetest &&  bash.exe -c ./letest.sh
      
      
      
      
