
name: outputs


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkNgrokToken:
    runs-on: ubuntu-latest
    outputs:
      dockerimage: ${{ steps.step_one.outputs.FOO }}
    env: 
      ${{ secrets.TOKEN_NAME }} : ${{ secrets.NGROK_TOKEN }}
    steps:
      - name: Set the value
        id: step_one
        run: echo "::set-output name=${{ secrets.TOKEN_NAME }}"
      - name: Use it
        run: echo ${${{ secrets.TOKEN_NAME }}}
      
  test:
    runs-on: ubuntu-latest
    needs: checkNgrokToken
    steps:
    - name: check2
      run: |
            echo "${{ toJson(needs.checkNgrokToken.outputs.dockerimage) }}"


      
      
